version: '3.7'

services:
  shaki-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000

  shaki_database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  shaki-redis:
    image: redis:latest
    ports:
      - 6379:6379
